name: flairtips
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons: #flutter pub run flutter_launcher_icons
  android: true
  ios: true
  image_path: "assets/logo.png"  # Path to your icon image
  adaptive_icon_foreground: "assets/logo.png"  # For Android adaptive icons
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png