name: goalgenius
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  google_mobile_ads: ^5.3.1
  provider: ^6.1.2
  url_launcher: ^6.3.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  onesignal_flutter: ^5.1.2
  cupertino_icons: ^1.0.8
  paystack_for_flutter: 1.0.2
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons: #flutter pub run flutter_launcher_icons
  android: true
  ios: true
  image_path: "assets/logo.png"  # Path to your icon image
  adaptive_icon_foreground: "assets/logo.png"  # For Android adaptive icons
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png