// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdzgeQpJyKlalVoQ-q4-msajNdgss6OGU',
    appId: '1:988342307794:web:7b6093345325be89f4d60b',
    messagingSenderId: '988342307794',
    projectId: 'football2024-f741a',
    authDomain: 'football2024-f741a.firebaseapp.com',
    storageBucket: 'football2024-f741a.appspot.com',
    measurementId: 'G-GKR00LWSND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyFiTQQBiUqMj7_Qsm37Vfn26BoLiPFi8',
    appId: '1:988342307794:android:c688d8cc344dc929f4d60b',
    messagingSenderId: '988342307794',
    projectId: 'football2024-f741a',
    storageBucket: 'football2024-f741a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoD6fcU4hChrT1iwHfAhIZ4yL6ZkKHaY0',
    appId: '1:988342307794:ios:ccf397484f27ec13f4d60b',
    messagingSenderId: '988342307794',
    projectId: 'football2024-f741a',
    storageBucket: 'football2024-f741a.appspot.com',
    iosBundleId: 'com.goalgenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoD6fcU4hChrT1iwHfAhIZ4yL6ZkKHaY0',
    appId: '1:988342307794:ios:ccf397484f27ec13f4d60b',
    messagingSenderId: '988342307794',
    projectId: 'football2024-f741a',
    storageBucket: 'football2024-f741a.appspot.com',
    iosBundleId: 'com.goalgenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdzgeQpJyKlalVoQ-q4-msajNdgss6OGU',
    appId: '1:988342307794:web:3eaf6cae1b5be7abf4d60b',
    messagingSenderId: '988342307794',
    projectId: 'football2024-f741a',
    authDomain: 'football2024-f741a.firebaseapp.com',
    storageBucket: 'football2024-f741a.appspot.com',
    measurementId: 'G-DPG7Y78RJH',
  );
}
